import os
from dotenv import load_dotenv

load_dotenv()

ELASTICSEARCH_URL = os.getenv("ELASTICSEARCH_URL")
CANDIDATE_API_URL = os.getenv("CANDIDATE_SERVICE_URL")
RABBITMQ_HOST=os.getenv("RABBITMQ_HOST")
RABBITMQ_PORT=os.getenv("RABBITMQ_PORT")
RABBITMQ_USER=os.getenv("RABBITMQ_USER")
RABBITMQ_PASS=os.getenv("RABBITMQ_PASS")
CANDIDATE_EXCHANGE_NAME=os.getenv("CANDIDATE_EXCHANGE_NAME")